version: '3.8'
services:
  frontend:
    build:
      context: ./front-operacionales
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend-operacionales
    ports:
      - "8080:8080"
