name: Deploy Backend to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build the backend
        run: |
          cd backend-operacionales
          cd api
          mvn clean package -DskipTests

      - name: Set Heroku Buildpack
        run: |
          heroku buildpacks:set heroku/java --app operacionales-back

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: operacionales-back
          heroku_email: juanseb.gav02@gmail.com
          appdir: ./backend-operacionales/api
